### ISSUE TITLE
请问有升级Mojave的计划吗

### ISSUE THREAD

**Issue by lclancey** [ArisHub/Hackintosh_Envy13_10.13.6#1]
RT 缺乏水平和时间自己钻研 只能使用别人现成的配置文件 很惭愧
大佬有升级Mojave的话烦请共享一份 不胜感激 没有的话我就用这个了
本人配置是ad173cl

**Comment by strconv** [comment]
已更新Mojave，加群有持续更新，群号在介绍文档
